project:
  type: website

website:
  title: "Yiqian Liu"
  navbar:
    left:
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/lyiqian
format:
  html:
    theme: cosmo
    css: styles.css



