project:
  type: website
  resources:
    - static/cv-public.pdf

website:
  title: "Yiqian Liu"
  navbar:
    left:
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/lyiqian
  comments:
    giscus:
      repo: lyiqian/lyiqian.github.io

format:
  html:
    theme: cosmo
    css: styles.css



